// Generated by CoffeeScript 1.6.3
(function() {
  Ext.define('app.view.human.Arm', {
    extend: 'app.helpers.kinetic.ComponentWrapper',
    config: {
      points: {
        a: [1, 0],
        b: [1.15, 1 / 4],
        c: [0.3, 1],
        d: [0, 1]
      },
      bodyDensity: 0.05
    },
    drawFunction: function(ctx, width, height) {
      var bd, p;
      p = this.getPoints();
      bd = this.getBodyDensity() * 2;
      ctx.moveTo(p.a.x(), p.a.y());
      this.deflectionPoint(p.a, p.b, 0.5);
      this.deflectionPoint(p.b, p.c, -bd * 0.7);
      this.deflectionPoint(p.c, p.d, 0.1);
      this.deflectionPoint(p.d, p.a, bd * 1.0);
      this.handPlaceholder = {
        x: (p.c.x() + p.d.x()) / 2,
        y: (p.c.y() + p.d.y()) / 2
      };
    },
    applyBodyDensity: function(val) {
      this.invalidate();
      return val;
    }
  });

}).call(this);

//# sourceMappingURL=Arm.map
