// Generated by CoffeeScript 1.6.3
(function() {
  Ext.define('app.view.human.Corps', {
    extend: 'app.helpers.kinetic.ComponentWrapper',
    config: {
      points: {
        a: [-2 / 6, 0],
        b: [2 / 6, 0],
        c: [3 / 6, 1],
        d: [-3 / 6, 1]
      },
      bodyDensity: 0.05,
      centerX: 0.5
    },
    drawFunction: function(ctx, width, height) {
      var bd, p;
      p = this.getPoints();
      ctx.moveTo(p.a.x(), p.a.y());
      bd = this.getBodyDensity() - 0.3;
      this.deflection(p.a.x(), p.a.y(), p.b.x(), p.b.y(), bd * 2);
      this.deflection(p.b.x(), p.b.y(), p.c.x(), p.c.y(), -bd);
      this.deflection(p.c.x(), p.c.y(), p.d.x(), p.d.y(), -bd);
      this.deflection(p.d.x(), p.d.y(), p.a.x(), p.a.y(), -bd);
    },
    applyBodyDensity: function(val) {
      this.invalidate();
      return val;
    }
  });

}).call(this);

//# sourceMappingURL=Corps.map
