// Generated by CoffeeScript 1.6.3
(function() {
  Ext.define('app.view.human.Hand', {
    extend: 'app.helpers.kinetic.ShapeWrapper',
    config: {
      points: {
        a: [0, 0],
        b: [0.5, 0.5],
        c: [-1.5, 4.8],
        d: [-2.4, 5]
      },
      bodyDensity: 0.05
    },
    drawFunction: function(ctx, width, height) {
      var p;
      p = this.getPoints();
      ctx._context.arc(0, 0, width, 0, 2 * Math.PI, false);
    },
    applyBodyDensity: function(val) {
      this.invalidate();
      return val;
    }
  });

}).call(this);

//# sourceMappingURL=Hand.map
