// Generated by CoffeeScript 1.6.3
(function() {
  Ext.define('app.view.human.RightArm', {
    extend: 'app.helpers.kinetic.ShapeWrapper',
    config: {
      points: {
        a: [0, 0],
        b: [-0.5, 0.5],
        c: [1.5, 4.8],
        d: [2.4, 5]
      },
      bodyDensity: 0.05
    },
    drawFunction: function(ctx, width, height) {
      var bd, p;
      p = this.getPoints();
      bd = this.getBodyDensity() - 0.5;
      ctx.moveTo(p.a.x(), p.a.y());
      this.deflectionPoint(p.a, p.b, 1);
      this.deflectionPoint(p.b, p.c, bd * 0.7);
      this.deflectionPoint(p.c, p.d, 0.1);
      this.deflectionPoint(p.d, p.a, -bd * 0.6);
    },
    applyBodyDensity: function(val) {
      this.invalidate();
      return val;
    }
  });

}).call(this);

//# sourceMappingURL=RightArm.map
