// Generated by CoffeeScript 1.6.3
(function() {
  Ext.application({
    requires: ['app.view.AppView'],
    name: 'app',
    appFolder: 'e-dietetyk/js/app',
    launch: function() {
      return Ext.create('app.view.AppView', {});
    }
  });

}).call(this);

//# sourceMappingURL=app.map
