// Generated by CoffeeScript 1.6.3
(function() {
  Ext.define('app.view.human.Breast', {
    extend: 'app.helpers.kinetic.ComponentWrapper',
    config: {
      bodyDensity: 0.5,
      age: 1,
      female: false,
      autoClose: false,
      initialAttrs: {
        strokeWidth: 1.54,
        fill: 'transparent',
        stroke: '#066A00',
        strokeEnabled: true,
        strokeScaleEnabled: true
      }
    },
    drawFunction: function(ctx, width, height) {
      var bd, female, xa, xb, xc, xd, ya, yb, yc, yd;
      female = this.getFemale();
      bd = this.getBodyDensity();
      if (female) {
        bd *= 0.7;
        bd += 0.2;
      } else {
        bd *= 0.3;
        bd += 0.05;
      }
      if (female) {
        xa = 0;
        xb = 0.25 - bd - this.getAge() / 50 / 3;
        xc = 0.75 + bd * 0.5;
        xd = 1;
        ya = 1 / 3;
        yb = 1 / 3 + bd + this.getAge() / 50 / 3;
        yc = 1 / 3 + bd + this.getAge() / 50 / 3;
        yd = 1 / 3 + bd * 0.3;
      } else {
        xa = 0;
        xb = 0.25;
        xc = 0.75;
        xd = 1;
        ya = 1 / 3;
        yb = 1 / 3 + bd;
        yc = 1 / 3 + bd;
        yd = 1 / 3;
      }
      this.currentContext.moveTo(this.normalizeX(xa), this.normalizeY(ya));
      this.bezier3Relative(xb, yb, xc, yc, xd, yd);
    },
    applyBodyDensity: function(val) {
      this.invalidate();
      return val;
    }
  });

}).call(this);
