// Generated by CoffeeScript 1.6.3
(function() {
  Ext.define('app.view.human.Neck', {
    extend: 'app.helpers.kinetic.ComponentWrapper',
    config: {
      points: {
        a: [1 / 4, 0],
        b: [3 / 4, 0],
        c: [1, 1],
        d: [0, 1]
      },
      bodyDensity: 0.05
    },
    drawFunction: function(ctx, width, height) {
      var bd, p;
      p = this.getPoints();
      bd = this.getBodyDensity() - 0.3;
      ctx.moveTo(p.a.x(), p.a.y());
      this.deflectionPoint(p.a, p.b, -0.2);
      this.deflectionPoint(p.b, p.c, -bd);
      this.deflectionPoint(p.c, p.d, -0.2);
      this.deflectionPoint(p.d, p.a, -bd);
    },
    applyBodyDensity: function(val) {
      this.invalidate();
      return val;
    }
  });

}).call(this);

//# sourceMappingURL=Neck.map
