// Generated by CoffeeScript 1.6.3
(function() {
  Ext.application({
    requires: ['app.view.AppView', 'app.view.ScheduleView'],
    name: 'app',
    appFolder: '../e-dietetyk/js/app',
    launch: function() {
      app.url = function(url) {
        return "../" + url;
      };
      Ext.fly('ext-loading-spinner').remove();
      Ext.fly('ext-body-density-panel').show({
        duration: 1000,
        delay: 1000
      });
      Ext.create('app.view.AppView', {
        renderTo: Ext.Element.get('ext-app-container')
      });
      return Ext.fly('ext-app-container').show({
        duration: 1000
      });
    }
  });

}).call(this);
