// Generated by CoffeeScript 1.6.3
(function() {
  Ext.define('app.helpers.kinetic.LayerWrapper', {
    extend: 'app.helpers.kinetic.BaseContainerWrapper'
  });

}).call(this);

//# sourceMappingURL=LayerWrapper.map
