// Generated by CoffeeScript 1.6.3
(function() {
  Ext.define('app.helpers.CanvasWrapper', {
    extend: 'Ext.Component',
    _applyListeners: function() {
      return this.on({
        scope: this,
        resize: function(self, width, height) {
          this.canvas.width = width;
          this.canvas.height = height;
          return this.render(width, height);
        },
        render: function() {
          this.getEl().appendChild(this.canvas);
          return this.render(this.getWidth(), this.getHeight());
        }
      }, this.canvas = Ext.DomHelper.createDom({
        tag: 'canvas'
      }));
    },
    constructor: function(config) {
      if (config == null) {
        config = {};
      }
      this.callParent(arguments);
      this._applyListeners();
    },
    render: function() {},
    getCanvas: function() {
      return this.canvas;
    }
  });

}).call(this);

//# sourceMappingURL=CanvasWrapper.map
