// Generated by CoffeeScript 1.6.3
(function() {
  Ext.define("app.model.ActivityModel", {
    extend: "Ext.data.Model",
    fields: [
      {
        name: "type",
        type: "string"
      }, {
        name: "name",
        type: "string"
      }, {
        name: 'dayPart',
        type: 'string'
      }, {
        name: 'weekDay',
        type: 'string'
      }, {
        name: 'duration',
        type: 'number'
      }
    ]
  });

}).call(this);
