Uzytkownicy:
    type: entity
    table: uzytkownicy
    id:
        login:
            type: string
            nullable: false
            length: 31
            fixed: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
        data:
            type: string
            nullable: false
            length: 20000
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
