// Generated by CoffeeScript 1.6.3
(function() {
  Ext.define('app.helpers.kinetic.GroupWrapper', {
    extend: 'app.helpers.kinetic.BaseWrapper',
    updateLayout: function(x, y, w, h) {
      this.kineticObject.setX(x);
      this.kineticObject.setY(y);
      return this.callParent(arguments);
    }
  });

}).call(this);

//# sourceMappingURL=GroupWrapper.map
