// Generated by CoffeeScript 1.6.3
(function() {
  Ext.define('app.helpers.kinetic.GroupWrapper', {
    extend: 'app.helpers.kinetic.BaseContainerWrapper',
    alias: 'kinetic.wrapper.group',
    updateLayout: function(x, y, w, h) {
      this.kineticObject.setX(x);
      this.kineticObject.setY(y);
      return this.callParent(arguments);
    },
    constructor: function(config) {
      return this.callParent([config, new Kinetic.Group()]);
    }
  });

}).call(this);

//# sourceMappingURL=GroupWrapper.map
