// Generated by CoffeeScript 1.6.3
(function() {
  Ext.define('app.helpers.kinetic.LayoutHelper', {
    config: {
      points: {},
      margin: 0
    },
    calculateBounds: function() {},
    constructor: function(config) {},
    setSize: function(width, height) {
      this.currentWidth = width;
      return this.currentHeight = height;
    },
    absX: function(relativeX) {
      return relativeX * this.currentWidth;
    },
    absY: function(relativeY) {
      return relativeY * this.currentHeight;
    }
  });

}).call(this);

//# sourceMappingURL=LayoutHelper.map
