// Generated by CoffeeScript 1.6.3
(function() {
  Ext.define('app.helpers.kinetic.ShapeWrapper', {
    config: {
      initialAttrs: {
        fill: "#00D2FF",
        stroke: "black",
        strokeWidth: 4
      }
    },
    constructor: function(config) {
      var me, shapeConfig;
      this.initConfig(config);
      this.callParent(arguments);
      me = this;
      shapeConfig = this.getInitialAttrs();
      shapeConfig.drawFunc = function(context) {
        var height, width;
        context.beginPath();
        width = this.getWidth();
        height = this.getHeight();
        me.drawFunction(context, width, height);
        context.closePath();
        return context.fillStrokeShape(this);
      };
      return this.kineticShape = new Kinetic.Shape(shapeConfig);
    },
    drawFunction: function(ctx, width, height) {
      ctx.drawRect(0, 0, width, height);
    },
    setAttrs: function(attrs) {
      return this.kineticShape.setAttrs(attrs);
    },
    get: function() {
      return this.kineticShape;
    }
  });

}).call(this);

//# sourceMappingURL=ShapeWrapper.map
