// Generated by CoffeeScript 1.6.3
(function() {
  Ext.define('app.helpers.kinetic.ShapeWrapper', {
    extend: 'app.helpers.kinetic.BaseWrapper',
    updateLayout: function(x, y, w, h) {
      this.callParent(arguments);
      this.kineticObject.setWidth(w);
      return this.kineticObject.setHeight(h);
    }
  });

}).call(this);

//# sourceMappingURL=ShapeWrapper.map
