diet_homepage:
  pattern:  /
  defaults: { _controller: DietBundle:Default:index }
diet_profile:
  pattern: /twoj_profil
  defaults: { _controller: DietBundle:Default:profile }
diet_profile_update:
  pattern: /twoj_profil_aktualizuj
  defaults: { _controller: DietBundle:Async:profile }
diet_diet:
  pattern:  /twoja_dieta
  defaults: { _controller: DietBundle:Default:diet }
diet_diet_details:
  pattern:  /twoja_dieta_szczegoly
  defaults: { _controller: DietBundle:Default:dietDetails }
diet_diet_plan:
  pattern:  /plan_diety
  defaults: { _controller: DietBundle:Default:dietPlan }
diet_diet_update:
  pattern:  /twoja_dieta_aktualizuj
  defaults: { _controller: DietBundle:Async:dietDetails }
diet_products:
  pattern:  /polecane_produkty
  defaults: { _controller: DietBundle:Default:products }
diet_customers:
  pattern:  /nasi_klienci
  defaults: { _controller: DietBundle:Default:customers }
diet_about:
  pattern:  /o_nas
  defaults: { _controller: DietBundle:Default:about }
diet_orders:
  pattern:  /twoje_zamowienia
  defaults: { _controller: DietBundle:Default:orders }
diet_orders_details:
  pattern:  /twoje_zamowienia_szczegoly
  defaults: { _controller: DietBundle:Default:ordersDetails }
diet_orders_update:
  pattern:  /twoje_zamowienia_aktualizuj
  defaults: { _controller: DietBundle:Async:orderDetails }
diet_contact:
  pattern:  /kontakt
  defaults: { _controller: DietBundle:Default:contact }
diet_test:
  pattern: /test
  defaults: { _controller: DietBundle:Default:test }
